name: Continuous Integration - Rest Backend Service
on: ["push", "pull_request"]

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun Environment
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.17

      - name: Install dependencies
        run: bun install

        # outputs coverage/lcov.info
      - name: Run tests
        env:
          DEV_MODE: true
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          HEROKU_API_TOKEN: ${{ secrets.HEROKU_API_TOKEN }}
          DEV_ACCESS_PASSPHRASE: ${{ secrets.DEV_ACCESS_PASSPHRASE }}

          GITHUB_APP_CLIENT_ID: ${{ secrets.GH_APP_CLIENT_ID }}
          GITHUB_APP_CLIENT_SECRET: ${{ secrets.GH_APP_CLIENT_SECRET }}
          GITHUB_APP_ID: ${{ secrets.GH_APP_ID }}
          GITHUB_APP_PRIVATE_KEY: ${{ secrets.GH_APP_PRIVATE_KEY }}
          GITHUB_APP_WEBHOOK_SECRET: ${{ secrets.GH_APP_WEBHOOK_SECRET }}
        run: |
          bun test --coverage --coverage-reporter lcov --coverage-dir coverage
          ls -lah coverage

        # generate coverage-report.json (not a json-summary) from lcov.info
      #- name: Generate Coverage Summary
      #  run: |
      #    bunx lcov-parse ./coverage/lcov.info > coverage/coverage-summary.json
      #    ls -lah coverage
      #    cat ./coverage/coverage-report.json

        # generate coverage-summary.json from lcov.info
      - name: Generate Coverage Summary
        run: |
          echo Coverage Summary
          bunx lcov-total ./coverage/lcov.info
          echo %
          
          coverage_percent=$(bunx lcov-total ./coverage/lcov.info)
          echo "{
            \"totals\": {
              \"percent_covered\": $coverage_percent
            }
          }" > coverage/coverage-summary.json
          
          ls -lah coverage
          cat ./coverage/coverage-summary.json

        # requires ./coverage/coverage-summary.json
      - name: Update Coverage Badge
        if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        uses: jaywcjlove/coverage-badges-cli@main
        with:
          style: flat-square
          source: coverage/coverage-summary.json
          output: coverage/coverage.svg
          jsonPath: totals.percent_covered
          label: coverage

      - name: Deploy Coverage Badge
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./coverage
