version: "3.8"

services:
  nginx-php:
    image: propromo/php-website:latest
    container_name: propromo-website
    restart: always
    env_file:
      - path: ../.env.docker # .env.docker.example
        required: true
    ports:
      - "80:80"
    networks:
      - propromo-network

  postgres:
    image: postgres:16.2
    container_name: propromo-database
    restart: always
    environment:
      POSTGRES_DB: propromo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: propromo
    ports:
      - "5432:5432"
    networks:
      - propromo-network

  redis:
    image: redis:6.2-alpine
    container_name: propromo-cache
    restart: always
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache:/data
    ports:
      - "6379:6379"
    networks:
      - propromo-network

volumes:
  cache:
    driver: local

networks:
  propromo-network:
    driver: bridge
