version: "3.8"

services:
  redis:
    image: redis:6.2-alpine
    container_name: propromo-cache
    restart: always
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache:/data
    ports:
      - "6379:6379"

volumes:
  cache:
    driver: local
