apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: propromo-database
  namespace: argocd
spec:
  project: propromo
  source:
    repoURL: https://github.com/propromo-software/propromo.ops
    path: database
  destination:
    name: leocloud
    namespace: student-it200250
